### ISSUE TITLE
Fix all checks and tests

### ISSUE THREAD

**Issue by stitam** [ELTEbioinformatics/mulea#4]

**Comment by stitam** [comment]
Failure (testHelpersAndUtilsTest.R:71:3): Utils : write_gmt
modelDfFromFile$ontology_name (`actual`) not equal to "Imagin gen ontology to tests." (`expected`).

`actual`:   "\\"Imagin gen ontology to tests.\\""
`expected`: "Imagin gen ontology to tests."    

When importing a gmt file, the second column may or may not include "\\"-s at start and end.

Related commits:

* `54f527183a11e2a4449470e4916bcde2c886ac1e` by @koralgooll removed lines from `gmtAsDf` on 2023-11-23
* `90a34b198f987f5b9ac68ed6221f402a727c46f6` by @olbeimarton reintroduced these lines on 2024-01-23

What is the expected behaviour? Thanks.

**Comment by barizona** [comment]
when running the `devtools:test()` function now I get the followings:

✔ | F W  S  OK | Context
✔ |         18 | testHelpersAndUtilsTest                                                 
✖ | 1       16 | testHypergeometricTest [17.4s]                                          
─────────────────────────────────────────────────────────────────────────────────────────
Error (testHypergeometricTest.R:257:3): ora : DB1 + DB2 => pool, matrix 2,2,2,0 and 2,2,1,3.
Error in ``[.data.frame`(gmtAsDF, c("ontology_id", "ontology_name", "list_of_values"))`: undefined columns selected
Backtrace:
    ▆
 1. └─mulea::read_gmt(...) at testHypergeometricTest.R:257:3
 2.   ├─gmtAsDF[c("ontology_id", "ontology_name", "list_of_values")] at mulea/R/Utils.R:49:3
 3.   └─base::`[.data.frame`(...) at mulea/R/Utils.R:49:3
─────────────────────────────────────────────────────────────────────────────────────────
✔ |          1 | testPermTest [2.0s]                                                     
✖ | 3        5 | testSubramanianTest                                                     
─────────────────────────────────────────────────────────────────────────────────────────
Failure (testSubramanianTest.R:51:3): GSEA : out of ontology elements.
muleaTestRes$pValue (`actual`) not equal to 151/495 (`expected`).

`actual` is NULL
`expected` is a double vector (0.305050505050505)

Failure (testSubramanianTest.R:77:3): GSEA : DB1 + DB2.
muleaTestRes$pValue (`actual`) not equal to c(169/330, 107/219) (`expected`).

`actual` is NULL
`expected` is a double vector (0.512121212121212, 0.488584474885845)

Failure (testSubramanianTest.R:103:3): GSEA : DB1 + DB2 out of background_element_names.
muleaTestRes$pValue (`actual`) not equal to c(156/653, 251/492) (`expected`).

`actual` is NULL
`expected` is a double vector (0.238897396630934, 0.510162601626016)
─────────────────────────────────────────────────────────────────────────────────────────

══ Results ══════════════════════════════════════════════════════════════════════════════
Duration: 20.3 s

── Failed tests ─────────────────────────────────────────────────────────────────────────
Error (testHypergeometricTest.R:257:3): ora : DB1 + DB2 => pool, matrix 2,2,2,0 and 2,2,1,3.
Error in ``[.data.frame`(gmtAsDF, c("ontology_id", "ontology_name", "list_of_values"))`: undefined columns selected
Backtrace:
    ▆
 1. └─mulea::read_gmt(...) at testHypergeometricTest.R:257:3
 2.   ├─gmtAsDF[c("ontology_id", "ontology_name", "list_of_values")] at mulea/R/Utils.R:49:3
 3.   └─base::`[.data.frame`(...) at mulea/R/Utils.R:49:3

Failure (testSubramanianTest.R:51:3): GSEA : out of ontology elements.
muleaTestRes$pValue (`actual`) not equal to 151/495 (`expected`).

`actual` is NULL
`expected` is a double vector (0.305050505050505)

Failure (testSubramanianTest.R:77:3): GSEA : DB1 + DB2.
muleaTestRes$pValue (`actual`) not equal to c(169/330, 107/219) (`expected`).

`actual` is NULL
`expected` is a double vector (0.512121212121212, 0.488584474885845)

Failure (testSubramanianTest.R:103:3): GSEA : DB1 + DB2 out of background_element_names.
muleaTestRes$pValue (`actual`) not equal to c(156/653, 251/492) (`expected`).

`actual` is NULL
`expected` is a double vector (0.238897396630934, 0.510162601626016)

[ FAIL 4 | WARN 0 | SKIP 0 | PASS 40 ]

**Comment by barizona** [comment]
I solved the errors with the testHypergeometricTest by adding the model.gmt back to the inst/extdata folder

**Comment by barizona** [comment]
Now we have less FAILs:
`devtools::test()`
ℹ Testing mulea
✔ | F W  S  OK | Context
✔ |         18 | testHelpersAndUtilsTest                                                                                
✔ |         17 | testHypergeometricTest [19.0s]                                                                         
✔ |          1 | testPermTest [1.9s]                                                                                    
✖ | 3        5 | testSubramanianTest                                                                                    
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (testSubramanianTest.R:51:3): GSEA : out of ontology elements.
muleaTestRes$pValue (`actual`) not equal to 151/495 (`expected`).

`actual` is NULL
`expected` is a double vector (0.305050505050505)

Failure (testSubramanianTest.R:77:3): GSEA : DB1 + DB2.
muleaTestRes$pValue (`actual`) not equal to c(169/330, 107/219) (`expected`).

`actual` is NULL
`expected` is a double vector (0.512121212121212, 0.488584474885845)

Failure (testSubramanianTest.R:103:3): GSEA : DB1 + DB2 out of background_element_names.
muleaTestRes$pValue (`actual`) not equal to c(156/653, 251/492) (`expected`).

`actual` is NULL
`expected` is a double vector (0.238897396630934, 0.510162601626016)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 21.7 s

── Failed tests ────────────────────────────────────────────────────────────────────────────────────────────────────────
Failure (testSubramanianTest.R:51:3): GSEA : out of ontology elements.
muleaTestRes$pValue (`actual`) not equal to 151/495 (`expected`).

`actual` is NULL
`expected` is a double vector (0.305050505050505)

Failure (testSubramanianTest.R:77:3): GSEA : DB1 + DB2.
muleaTestRes$pValue (`actual`) not equal to c(169/330, 107/219) (`expected`).

`actual` is NULL
`expected` is a double vector (0.512121212121212, 0.488584474885845)

Failure (testSubramanianTest.R:103:3): GSEA : DB1 + DB2 out of background_element_names.
muleaTestRes$pValue (`actual`) not equal to c(156/653, 251/492) (`expected`).

`actual` is NULL
`expected` is a double vector (0.238897396630934, 0.510162601626016)

[ FAIL 3 | WARN 0 | SKIP 0 | PASS 41 ]
>

**Comment by barizona** [comment]
I have fixed this as well by changing p_value-s in the testSubramanianTest.R
