### ISSUE TITLE
Network plot nr. of elements

### ISSUE THREAD

**Issue by barizona** [ELTEbioinformatics/mulea#6]
The Nr. of shared elements on the network plot are still not natural values (see the updated README). Also, the colour scheme of the heatmap differs from the colour scheme of the other plots. @olbeimarton , you said that you changed this. Did you push it to Git Hub? I am also quite not sure that you pushed any changes in the help descriptions.

**Comment by olbeimarton** [comment]
I updated the heatmap color scale to match the others. @koralgooll I think you had a solution for the integer values on the axis.

**Comment by barizona** [comment]
I've solved it
