### ISSUE TITLE
Make all headers to snake_case

### ISSUE THREAD

**Issue by barizona** [ELTEbioinformatics/mulea#7]
The column headers in some mulea data frames are not snake_case. @olbeimarton , you said that you have corrected this, right?
in `run_test(gsea_model)`:

- nrCommonGenesOntologySet
- nrCommonGenesOntologyBackground
- pValue
- adjustedPValue

@koralgooll , what do the first 2 (nrCommonGenesOntologySet and nrCommonGenesOntologyBackground) mean?

**Comment by olbeimarton** [comment]
I replaced these with snake case versions.
